[workspace]
resolver = "3"
members = ["nodez", "nodez-demo", "nodez-derive"]
default-members = ["nodez-demo"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/andyhenshaw/nodez"

[workspace.dependencies]
egui = "0.36"
eframe = { version = "0.36", default-features = false, features = [
    "default_fonts",
    "glow",
    "wayland",
    "x11",
] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
