"""Type stubs for the `nodez` extension module."""

from typing import Any, Callable, Iterable, Sequence

__version__: str

Color = str | Sequence[float]
"""`"#RRGGBB"`, `"#RRGGBBAA"`, or an `(r, g, b[, a])` sequence of 0-255 ints or 0.0-1.0 floats."""

SocketAddr = tuple[int, str]
"""A socket, as `(node_id, socket_name)`."""

class Widget:
    """The inline editor drawn for a socket or a parameter."""
    @staticmethod
    def none() -> Widget: ...
    @staticmethod
    def checkbox() -> Widget: ...
    @staticmethod
    def text(hint: str = "", multiline: bool = False) -> Widget: ...
    @staticmethod
    def int(min: int = ..., max: int = ..., speed: float = 1.0, suffix: str = "") -> Widget: ...
    @staticmethod
    def float(min: float = ..., max: float = ..., speed: float = 0.01, suffix: str = "") -> Widget: ...
    @staticmethod
    def slider(min: float, max: float) -> Widget: ...
    @staticmethod
    def combo(options: Sequence[str]) -> Widget: ...
    @staticmethod
    def color(alpha: bool = False) -> Widget: ...
    @staticmethod
    def vec2(speed: float = 0.01) -> Widget: ...
    @staticmethod
    def vec3(speed: float = 0.01) -> Widget: ...

class Socket:
    """One input or output socket of a template."""
    def __init__(
        self,
        name: str,
        type_name: str,
        *,
        label: str | None = None,
        widget: Widget | None = None,
        default: Any = None,
        multi: bool = False,
        hidden: bool = False,
        description: str = "",
    ) -> None: ...

class Param:
    """A node property that is not a socket: always drawn, never connectable."""
    def __init__(
        self,
        name: str,
        widget: Widget,
        *,
        label: str | None = None,
        default: Any = None,
        show_label: bool = True,
        description: str = "",
    ) -> None: ...

class Library:
    """The socket types and node templates of your domain."""
    def __init__(self) -> None: ...
    def add_type(
        self,
        name: str,
        color: Color,
        *,
        shape: str = "circle",
        label: str | None = None,
        wildcard: bool = False,
        description: str = "",
    ) -> str:
        """Register a socket type. `shape` is circle, diamond, diamond_dot or square."""
    def allow_cast(self, from_type: str, to_type: str) -> None:
        """Let an output of `from_type` feed an input of `to_type`."""
    def allow_cast_both(self, a: str, b: str) -> None: ...
    def compatible(self, from_type: str, to_type: str) -> bool: ...
    def set_category_color(self, category: str, color: Color) -> None: ...
    def add_template(
        self,
        id: str,
        label: str,
        *,
        category: str = "Misc",
        inputs: Sequence[Socket] | None = None,
        outputs: Sequence[Socket] | None = None,
        params: Sequence[Param] | None = None,
        width: float = 150.0,
        description: str = "",
        keywords: Sequence[str] | None = None,
        header_color: Color | None = None,
    ) -> str: ...
    def type_names(self) -> list[str]: ...
    def template_ids(self) -> list[str]: ...
    def categories(self) -> list[str]: ...
    def inputs_of(self, template: str) -> list[str]: ...
    def outputs_of(self, template: str) -> list[str]: ...
    def __len__(self) -> int: ...

class EvalNode:
    """The node being evaluated, as handed to an `evaluate` callback."""
    id: int
    type: str
    title: str
    muted: bool
    params: dict[str, Any]
    literals: dict[str, Any]
    def param(self, name: str, default: Any = None) -> Any: ...
    def literal(self, name: str, default: Any = None) -> Any: ...
    def is_linked(self, name: str) -> bool: ...
    def input(self, name: str) -> Any:
        """The first upstream result at an input socket, or None."""
    def inputs(self, name: str) -> list[Any]:
        """Every upstream result at an input socket, in connection order."""
    def resolve(self, name: str, default: Any = None) -> Any:
        """Whatever is wired in, else the inline value."""

class Graph:
    """A directed acyclic graph of typed nodes."""
    node_count: int
    connection_count: int

    def __init__(self) -> None: ...
    @staticmethod
    def from_json(text: str, library: Library | None = None) -> Graph: ...
    def to_json(self) -> str: ...

    # nodes
    def add_node(self, library: Library, template: str,
                 position: tuple[float, float] = (0.0, 0.0)) -> int: ...
    def remove_node(self, id: int) -> bool: ...
    def contains_node(self, id: int) -> bool: ...
    def node_ids(self) -> list[int]: ...
    def node(self, library: Library, id: int) -> dict[str, Any]: ...
    def nodes(self, library: Library) -> list[dict[str, Any]]: ...
    def type_of(self, library: Library, id: int) -> str: ...
    def title(self, id: int) -> str: ...
    def set_title(self, id: int, title: str) -> None: ...
    def position(self, id: int) -> tuple[float, float]: ...
    def set_position(self, id: int, position: tuple[float, float]) -> None: ...
    def set_collapsed(self, id: int, collapsed: bool) -> None: ...
    def set_muted(self, id: int, muted: bool) -> None: ...

    # values
    def set_input(self, library: Library, id: int, socket: str, value: Any) -> None: ...
    def input_value(self, id: int, socket: str) -> Any: ...
    def set_param(self, library: Library, id: int, name: str, value: Any) -> None: ...
    def param(self, id: int, name: str) -> Any: ...

    # connections
    def connect(self, library: Library, from_: SocketAddr, to: SocketAddr) -> int:
        """Wire an output to an input. Raises ValueError if refused."""
    def why_not_connect(self, library: Library, from_: SocketAddr,
                        to: SocketAddr) -> str | None:
        """None if the link would be accepted, else why it would not."""
    def disconnect(self, connection_id: int) -> bool: ...
    def disconnect_socket(self, socket: SocketAddr) -> int: ...
    def connections(self) -> list[tuple[int, str, int, str]]: ...
    def connection_ids(self) -> list[int]: ...
    def source_of(self, id: int, socket: str) -> SocketAddr | None: ...
    def links_into(self, id: int, socket: str) -> list[SocketAddr]: ...
    def links_from(self, id: int, socket: str) -> list[SocketAddr]: ...
    def is_input_linked(self, id: int, socket: str) -> bool: ...

    # traversal
    def predecessors(self, id: int) -> list[int]: ...
    def successors(self, id: int) -> list[int]: ...
    def ancestors(self, id: int) -> list[int]: ...
    def descendants(self, id: int) -> list[int]: ...
    def depends_on(self, node: int, target: int) -> bool: ...
    def roots(self) -> list[int]: ...
    def sinks(self) -> list[int]: ...
    def isolated(self) -> list[int]: ...
    def topological_order(self) -> list[int]: ...
    def dependency_order(self, id: int) -> list[int]: ...
    def components(self) -> list[list[int]]: ...
    def depths(self) -> dict[int, int]: ...
    def find_cycle(self) -> list[int] | None: ...
    def is_acyclic(self) -> bool: ...

    # evaluation
    def evaluate(self, library: Library, target: int,
                 rule: Callable[[EvalNode], Any]) -> Any:
        """Fold what `target` depends on into a value, in dependency order."""
    def evaluate_all(self, library: Library,
                     rule: Callable[[EvalNode], Any]) -> dict[int, Any]: ...

    # utilities
    def layout(self, library: Library, column_gap: float = 70.0,
               row_gap: float = 22.0) -> None: ...
    def validate(self, library: Library) -> tuple[int, int]: ...
    def clear(self) -> None: ...
    def __len__(self) -> int: ...

def edit(
    library: Library,
    graph: Graph,
    *,
    title: str = "nodez",
    theme: str = "dark",
    scroll_mode: str = "auto",
    on_change: Callable[[Graph], str | None] | None = None,
    size: tuple[float, float] = (1280.0, 820.0),
) -> None:
    """Open the editor on `graph` and block until the window closes.

    `graph` is edited in place. `on_change` is called with the graph whenever it
    changes; anything it returns as a string is shown in a panel beside the
    canvas.
    """
